# Generated by Django 6.0.3 on 2026-04-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='linl',
            new_name='link',
        ),
    ]
